const tourStops = [
  {
    position: { lat: 43.1084097, lng: 141.3383695 },
    id: "N01",
    icon: "./img/N.svg",
    name: "麻生",
    door: "右",
    restroom: "改札内",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n01asabu20230922.pdf",
  },
  {
    position: { lat: 43.1008609, lng: 141.3418875 },
    id: "N02",
    icon: "./img/N.svg",
    name: "北34条",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n02kita34.pdf",
  },
  {
    position: { lat: 43.0899615, lng: 141.3446436 },
    id: "N03",
    icon: "./img/N.svg",
    name: "北24条",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n03kita24.pdf",
  },
  {
    position: { lat: 43.081577, lng: 141.3467425 },
    id: "N04",
    icon: "./img/N.svg",
    name: "北18条",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n04kita18.pdf",
  },
  {
    position: { lat: 43.0747575, lng: 141.3484953 },
    id: "N05",
    icon: "./img/N.svg",
    name: "北12条",
    door: "左",
    restroom: "改札内",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n05kita12.pdf",
  },
  {
    position: { lat: 43.0679978, lng: 141.3511417 },
    id: "N06",
    icon: "./img/N.svg",
    name: "さっぽろ",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/sapporo.pdf",
  },
  {
    position: { lat: 43.0601472, lng: 141.352223 },
    id: "N07",
    icon: "./img/N.svg",
    name: "大通",
    door: "左",
    restroom: "改札内／改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n7_t09_h08_odori.pdf",
  },
  {
    position: { lat: 43.0554512, lng: 141.3533139 },
    id: "N08",
    icon: "./img/N.svg",
    name: "すすきの",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n08susukino.pdf",
  },
  {
    position: { lat: 43.0484332, lng: 141.3551586 },
    id: "N09",
    icon: "./img/N.svg",
    name: "中島公園",
    door: "左",
    restroom: "改札内",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n09nakazima.pdf",
  },
  {
    position: { lat: 43.0403976, lng: 141.355759 },
    id: "N10",
    icon: "./img/N.svg",
    name: "幌平橋",
    door: "左",
    restroom: "改札内",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n10horohira.pdf",
  },
  {
    position: { lat: 43.0376569, lng: 141.3609502 },
    id: "N11",
    icon: "./img/N.svg",
    name: "中の島",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n11nakanoshima.pdf",
  },
  {
    position: { lat: 43.0345376, lng: 141.3683138 },
    id: "N12",
    icon: "./img/N.svg",
    name: "平岸",
    door: "左",
    restroom: "改札内",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n12hiragishi.pdf",
  },
  {
    position: { lat: 43.0267795, lng: 141.3713423 },
    id: "N13",
    icon: "./img/N.svg",
    name: "南平岸",
    door: "右",
    restroom: "改札内",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n13minamihiragishi.pdf",
  },
  {
    position: { lat: 43.0168122, lng: 141.3673217 },
    id: "N14",
    icon: "./img/N.svg",
    name: "澄川",
    door: "右",
    restroom: "改札内／改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n14sumikawa.pdf",
  },
  {
    position: { lat: 43.0060106, lng: 141.3647713 },
    id: "N15",
    icon: "./img/N.svg",
    name: "自衛隊前",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n15jieitaimae.pdf",
  },
  {
    position: { lat: 42.9912369, lng: 141.3584284 },
    id: "N16",
    icon: "./img/N.svg",
    name: "真駒内",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n16makomanai20230922.pdf",
  },
  {
    position: { lat: 43.08932, lng: 141.2757 },
    id: "T01",
    icon: "./img/T.svg",
    name: "宮の沢",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t01miyanosawa.pdf",
  },
  {
    position: { lat: 43.0811683, lng: 141.2907903 },
    id: "T02",
    icon: "./img/T.svg",
    name: "発寒南",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t02hassamuminami.pdf",
  },
  {
    position: { lat: 43.0755475, lng: 141.3042342 },
    id: "T03",
    icon: "./img/T.svg",
    name: "琴似",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t03kotoni.pdf",
  },
  {
    position: { lat: 43.070139, lng: 141.314407 },
    id: "T04",
    icon: "./img/T.svg",
    name: "二十四軒",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t04nijuyonken.pdf",
  },
  {
    position: { lat: 43.0610376, lng: 141.3145771 },
    id: "T05",
    icon: "./img/T.svg",
    name: "西28丁目",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t05nishi28.pdf",
  },
  {
    position: { lat: 43.0555951, lng: 141.3182692 },
    id: "T06",
    icon: "./img/T.svg",
    name: "円山公園",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t06maruyama.pdf",
  },
  {
    position: { lat: 43.0572083, lng: 141.3302988 },
    id: "T07",
    icon: "./img/T.svg",
    name: "西18丁目",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t07nishi18.pdf",
  },
  {
    position: { lat: 43.0586226, lng: 141.341109 },
    id: "T08",
    icon: "./img/T.svg",
    name: "西11丁目",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t08nishi11.pdf",
  },
  {
    position: { lat: 43.0603472, lng: 141.353723 },
    id: "T09",
    icon: "./img/T.svg",
    name: "大通",
    door: "右",
    restroom: "改札内／改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n7_t09_h08_odori.pdf",
  },
  {
    position: { lat: 43.0613254, lng: 141.3604141 },
    id: "T10",
    icon: "./img/T.svg",
    name: "バスセンター前",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t10buscenter.pdf",
  },
  {
    position: { lat: 43.0567284, lng: 141.3734212 },
    id: "T11",
    icon: "./img/T.svg",
    name: "菊水",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t11kikusui.pdf",
  },
  {
    position: { lat: 43.0517949, lng: 141.3847861 },
    id: "T12",
    icon: "./img/T.svg",
    name: "東札幌",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t12higashisapporo.pdf",
  },
  {
    position: { lat: 43.0462964, lng: 141.3959125 },
    id: "T13",
    icon: "./img/T.svg",
    name: "白石",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t13siroishi.pdf",
  },
  {
    position: { lat: 43.0403321, lng: 141.4110779 },
    id: "T14",
    icon: "./img/T.svg",
    name: "南郷7丁目",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t14nango7_1.pdf",
  },
  {
    position: { lat: 43.0357059, lng: 141.4227809 },
    id: "T15",
    icon: "./img/T.svg",
    name: "南郷13丁目",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t15nango13.pdf",
  },
  {
    position: { lat: 43.0304945, lng: 141.4347131 },
    id: "T16",
    icon: "./img/T.svg",
    name: "南郷18丁目",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t16nango18.pdf",
  },
  {
    position: { lat: 43.02731, lng: 141.4528 },
    id: "T17",
    icon: "./img/T.svg",
    name: "大谷地",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t17_oyachi.pdf",
  },
  {
    position: { lat: 43.0321649, lng: 141.4642854 },
    id: "T18",
    icon: "./img/T.svg",
    name: "ひばりが丘",
    door: "左",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t18hibarigaoka.pdf",
  },
  {
    position: { lat: 43.0385362, lng: 141.4738982 },
    id: "T19",
    icon: "./img/T.svg",
    name: "新さっぽろ",
    door: "右",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/t19_shinsapporo.pdf",
  },
  {
    position: { lat: 43.1130391, lng: 141.3671084 },
    id: "H01",
    icon: "./img/H.svg",
    name: "栄町",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h01sakaemachi.pdf",
  },
  {
    position: { lat: 43.1048068, lng: 141.3690872 },
    id: "H02",
    icon: "./img/H.svg",
    name: "新道東",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h02shindohigashi.pdf",
  },
  {
    position: { lat: 43.094267, lng: 141.3716283 },
    id: "H03",
    icon: "./img/H.svg",
    name: "元町",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h03motomachi.pdf",
  },
  {
    position: { lat: 43.082365, lng: 141.374338 },
    id: "H04",
    icon: "./img/H.svg",
    name: "環状通東",
    door: "",
    restroom: "改札外",
    url: "https://city.sapporo.jp/st/subway/ekikonaizu/documents/h04kanjodorihigashi.pdf",
  },
  {
    position: { lat: 43.078171, lng: 141.364978 },
    id: "H05",
    icon: "./img/H.svg",
    name: "東区役所前",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h05higashikuyakushomae.pdf",
  },
  {
    position: { lat: 43.0768068, lng: 141.3549245 },
    id: "H06",
    icon: "./img/H.svg",
    name: "北13条東",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h06kita13jphigashi.pdf",
  },
  {
    position: { lat: 43.0681978, lng: 141.3534417 },
    id: "H07",
    icon: "./img/H.svg",
    name: "さっぽろ",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/sapporo.pdf",
  },
  {
    position: { lat: 43.0605472, lng: 141.355423 },
    id: "H08",
    icon: "./img/H.svg",
    name: "大通",
    door: "",
    restroom: "改札内／改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/n7_t09_h08_odori.pdf",
  },
  {
    position: { lat: 43.0547877, lng: 141.3567871 },
    id: "H09",
    icon: "./img/H.svg",
    name: "豊水すすきの",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h09hosuisusukino.pdf",
  },
  {
    position: { lat: 43.0474994, lng: 141.3690212 },
    id: "H10",
    icon: "./img/H.svg",
    name: "学園前",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h10gakuenmae.pdf",
  },
  {
    position: { lat: 43.041992, lng: 141.376344 },
    id: "H11",
    icon: "./img/H.svg",
    name: "豊平公園",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h11toyohirakoen.pdf",
  },
  {
    position: { lat: 43.0362046, lng: 141.3853399 },
    id: "H12",
    icon: "./img/H.svg",
    name: "美園",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h12misono.pdf",
  },
  {
    position: { lat: 43.0301224, lng: 141.396617 },
    id: "H13",
    icon: "./img/H.svg",
    name: "月寒中央",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h13tukisamuchuo.pdf",
  },
  {
    position: { lat: 43.0214519, lng: 141.4032696 },
    id: "H14",
    icon: "./img/H.svg",
    name: "福住",
    door: "",
    restroom: "改札外",
    url: "https://www.city.sapporo.jp/st/subway/ekikonaizu/documents/h14fukuzumi.pdf",
  },
];
